const ADD_PARTICIPANT = "ADD_PARTICIPANT"
const REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT"
const SET_USER = "SET_USER"
const SET_USER_STREAM = "SET_USER_STREAM"
export {ADD_PARTICIPANT,REMOVE_PARTICIPANT,SET_USER,SET_USER_STREAM}