const ADD_PARTICIPANT = "ADD_PARTICIPANT"
const REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT"
const SET_USER = "SET_USER"
const SET_USER_STREAM = "SET_USER_STREAM"
const UPDATE_USER = "UPDATE_USER"
const UPDATE_PARTICIPANT = "UPDATE_PARTICIPANT"
export {ADD_PARTICIPANT,REMOVE_PARTICIPANT,SET_USER,SET_USER_STREAM,UPDATE_USER,UPDATE_PARTICIPANT}